version: '3.7'

volumes:
    logs:
        driver: local

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: develop
        networks:
            role_dices:
                aliases:
                    - role-dices-table
    nginx:
        build: ./docker-files/nginx
        ports:
            - 80:80
        volumes:
            - ./dices-api:/var/www
        depends_on:
            - dices
        networks:
            role_dices:
                aliases:
                    - role-dices-table
    dices:
        build: ./docker-files/php
        working_dir: /var/www
        environment:
            docker: "true"
        depends_on:
            - mongo
        ports:
            - 9000:9000
        volumes:
            - ./dices-api:/var/www
        networks:
            role_dices:
                aliases:
                    - role-dices-table

networks:
    role_dices:
        name: role-dices-network
