version: '3.7'

volumes:
    logs:
        driver: local

services:
    nginx:
        build: ./docker-files/nginx
        ports:
            - 80:80
        volumes:
            - ./dices-api:/var/www
        depends_on:
            - dices
        networks:
            role_dices:
                aliases:
                    - role-dices-table
    dices:
        build: ./docker-files/php
        working_dir: /var/www
        environment:
            docker: "true"
        ports:
            - 9000:9000
        volumes:
            - ./dices-api:/var/www
            - ./composer.phar:/var/www/composer.phar
        networks:
            role_dices:
                aliases:
                    - role-dices-table

networks:
    role_dices:
        name: role-dices-network
